/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SalesWorkArea;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Supplier.SupplierDirectory;

/**
 *
 * @author Tanmay Paawar
 */
public class SalesProcessOrReport extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    ProcessOrder processOrder;
    SalesPerformance salesPerformance ;
    SupplierDirectory supplierDirectory ; 
    
    /**
     * Creates new form SalesProcessOrReport
     */
    public SalesProcessOrReport(ProcessOrder processOrder ,SalesPerformance salesPerformance, JPanel CardSequencePanel, SupplierDirectory supplierDirectory) {
        initComponents();
        this.processOrder = processOrder;
        this.salesPerformance = salesPerformance ;
        this.CardSequencePanel = CardSequencePanel ; 
        this.supplierDirectory = supplierDirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalesPerformance = new javax.swing.JButton();
        btnProcessOrder = new javax.swing.JButton();

        btnSalesPerformance.setBackground(new java.awt.Color(102, 153, 255));
        btnSalesPerformance.setForeground(new java.awt.Color(255, 255, 255));
        btnSalesPerformance.setText("Sales Performance");
        btnSalesPerformance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalesPerformance.setMaximumSize(new java.awt.Dimension(200, 40));
        btnSalesPerformance.setMinimumSize(new java.awt.Dimension(20, 23));
        btnSalesPerformance.setPreferredSize(new java.awt.Dimension(240, 30));
        btnSalesPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesPerformanceIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnProcessOrder.setBackground(new java.awt.Color(102, 153, 255));
        btnProcessOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnProcessOrder.setText("Process Order");
        btnProcessOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProcessOrder.setMaximumSize(new java.awt.Dimension(200, 40));
        btnProcessOrder.setMinimumSize(new java.awt.Dimension(20, 23));
        btnProcessOrder.setPreferredSize(new java.awt.Dimension(240, 30));
        btnProcessOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessOrderIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(btnSalesPerformance, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(btnProcessOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addGap(197, 197, 197)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(btnSalesPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(135, Short.MAX_VALUE)
                    .addComponent(btnProcessOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(125, 125, 125)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalesPerformanceIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesPerformanceIdentifyResourceAssetsActionPerformed

//         ProcessOrder po = new ProcessOrder(CardSequencePanel, supplierDirectory);
//        CardSequencePanel.add("ProcessOrder", po);
//        CardLayout layout = (CardLayout)CardSequencePanel.getLayout();
//        layout.next(CardSequencePanel);
//
//            }
//        }
    }//GEN-LAST:event_btnSalesPerformanceIdentifyResourceAssetsActionPerformed

    private void btnProcessOrderIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessOrderIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcessOrderIdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessOrder;
    private javax.swing.JButton btnSalesPerformance;
    // End of variables declaration//GEN-END:variables
}
