/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminWorkArea;

import javax.swing.JPanel;
import model.Business.Business;

/**
 *
 * @author Tanmay Paawar
 */
public class AdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form BusinessManagerWorkArea
     */
    javax.swing.JPanel CardSequencePanel;
    Business business;

    public AdminWorkArea(Business b, JPanel clp) {
        business = b;
        this.CardSequencePanel = clp;
        initComponents();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageSupplier = new javax.swing.JButton();
        btnManageCustomer = new javax.swing.JButton();
        btnCustomerReport = new javax.swing.JButton();

        btnManageSupplier.setBackground(new java.awt.Color(102, 153, 255));
        btnManageSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnManageSupplier.setText("Manage Suppliers");
        btnManageSupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageSupplier.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageSupplier.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageSupplier.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSupplierActionPerformed(evt);
            }
        });

        btnManageCustomer.setBackground(new java.awt.Color(102, 153, 255));
        btnManageCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCustomer.setText("Manage Customers");
        btnManageCustomer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCustomer.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageCustomer.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageCustomer.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomerActionPerformed(evt);
            }
        });

        btnCustomerReport.setBackground(new java.awt.Color(102, 153, 255));
        btnCustomerReport.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerReport.setText("Performance Reports");
        btnCustomerReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCustomerReport.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCustomerReport.setMinimumSize(new java.awt.Dimension(20, 20));
        btnCustomerReport.setPreferredSize(new java.awt.Dimension(240, 25));
        btnCustomerReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnManageSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(btnManageCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btnCustomerReport, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomerReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSupplierActionPerformed
        // TODO add your handling code here:

        ManageSupplier iet = new ManageSupplier(CardSequencePanel, business);
        CardSequencePanel.add("ManageSupplier", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageSupplierActionPerformed

    private void btnManageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomerActionPerformed
//        // TODO add your handling code here:
//
        CardSequencePanel.removeAll();
//        ViewBusinessUnitRiskProfile drpd= new ViewBusinessUnitRiskProfile(businessunit, CardSequencePanel);
//        ManageHazards drpd = new ManageHazards(businessunit, CardSequencePanel);
//        CardSequencePanel.add("ManageRiskProfiles", drpd);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageCustomerActionPerformed

    private void btnCustomerReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerReportActionPerformed
        
        PerformanceReportWorkArea iet = new PerformanceReportWorkArea(CardSequencePanel, business);
        CardSequencePanel.add("PerformanceReportWorkArea", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnCustomerReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerReport;
    private javax.swing.JButton btnManageCustomer;
    private javax.swing.JButton btnManageSupplier;
    // End of variables declaration//GEN-END:variables
}
